name: Continuous Deployment

on:
    push:
        branches:
            - main

jobs:
    test:
        name: Test Application
        uses: otheypsy/paypal-web-integration-samples/.github/workflows/test.yml@main

    deploy:
        name: Deploy Application
        uses: otheypsy/paypal-web-integration-samples/.github/workflows/deploy.yml@main
