name: Continuous Deployment

on:
    push:
        branches:
            -   main

jobs:
    test:
        name: Test Application
        uses: otheypsy/paypal-web-integration-samples/.github/workflows/test.yml@main

    deploy:
        name: Deploy Application
        needs: [test]
        uses: otheypsy/paypal-web-integration-samples/.github/workflows/deploy.yml@main
        secrets:
            SSH_HOST: ${{ secrets.SSH_HOST }}
            SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
            SSH_KEY: ${{ secrets.SSH_KEY }}
            SSH_PORT: ${{ secrets.SSH_PORT }}
