name: Test Application

on:
    workflow_call:

jobs:

    test:

        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [18.x]

        steps:
            -   name: checkout branch
                uses: actions/checkout@v3

            -   name: use Node.js ${{ matrix.node-version }}
                uses: actions/setup-node@v3
                with:
                    node-version: ${{ matrix.node-version }}

            -   name: install node modules
                run: yarn install
                env:
                    CI: true

            -   name: test node app
                run: yarn test
                env:
                    CI: true
